# Generated by Django 4.1.6 on 2023-02-13 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boughts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripePrice',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='boughts.item')),
            ],
        ),
    ]
